Fix `nonetype` by adding `ensure_required_libs` to `get_conn_params` in postgres.py (#253)
* Update README.md to remove Ansible 2.9 & 2.10

* Update version.py comment to remove references to Ansible version 2.9 & 2.10

* Update changelog

* Updated to include feedback from @Andersson007i

* Fix: add call to ensure required libraries in get_conn_params

added `ensure_required_libs(module)` to `get_conn_params` to ensure a meaningful error is thrown when psycopg2 is not installed. Without this change the error was; `AttributeError: 'NoneType' object has no attribute '__version__'`.

Fixes #252

* add changelog fragment

* Update changelog fragment based on Andrew's feedback.

* change the `ensure_required_libs(module)` call to be in every module rather than just the definition for clarity.

* Add ensure_required_libs to import. Was missing from my last commit.

* Fix module to be self.module

* Remove redundant ensure_required_libs(module) call since it's now called explicitly in each module.